python train.py --num-layer 2 --act ReLU --feature-type 0
python train.py --num-layer 2 --act ReLU --feature-type 1
python train.py --num-layer 2 --act ReLU --feature-type 2
python train.py --num-layer 2 --act GLU --feature-type 0
python train.py --num-layer 2 --act GLU --feature-type 1
python train.py --num-layer 2 --act GLU --feature-type 2
python train.py --num-layer 3 --act ReLU --feature-type 0
python train.py --num-layer 3 --act ReLU --feature-type 1
python train.py --num-layer 3 --act ReLU --feature-type 2
python train.py --num-layer 3 --act GLU --feature-type 0
python train.py --num-layer 3 --act GLU --feature-type 1
python train.py --num-layer 3 --act GLU --feature-type 2
python train.py --num-layer 4 --act ReLU --feature-type 0
python train.py --num-layer 4 --act ReLU --feature-type 1
python train.py --num-layer 4 --act ReLU --feature-type 2
python train.py --num-layer 4 --act GLU --feature-type 0
python train.py --num-layer 4 --act GLU --feature-type 1
python train.py --num-layer 4 --act GLU --feature-type 2
